name: Naemon
highlighter: rouge
paginate: 10
paginate_path: "news/page:num"

# site specific variables
release_version: 1.0.6
release_date: 23 Jan 2017

# custom "tags"
hint: '<div class="alert alert-success" style="margin: 10px;"><i class="glyphicon glyphicon-thumbs-up"></i> <b>Tip</b>:&nbsp;'
note: '<div class="alert alert-info" style="margin: 10px;"><i class="glyphicon glyphicon-pencil"></i> <b>Note</b>:&nbsp;'
info: '<div class="alert alert-info" style="margin: 10px;"><i class="glyphicon glyphicon-info-sign"></i>&nbsp;'
warn: '<div class="alert alert-warning" style="margin: 10px;"><i class="glyphicon glyphicon-exclamation-sign"></i> <b>Warning:</b>&nbsp;'
warning: '<div class="alert alert-warning" style="margin: 10px;"><i class="glyphicon glyphicon-exclamation-sign"></i> <b>Warning:</b>&nbsp;'
danger: '<div class="alert alert-danger" style="margin: 10px;"><i class="glyphicon glyphicon-exclamation-sign"></i> <b>Danger:</b>&nbsp;'
end: '</div>'

exclude:
    - "*.tpl"
    - "t/*"
    - "*/update"
